version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./my.ini:/etc/mysql/conf.d/my_custom.ini
    ports:
      - 3306:3306